import './global.css';
import { UiLayout } from '@/components/ui/ui-layout';
import { ClusterProvider } from '@/components/cluster/cluster-data-access';
import { SolanaProvider } from '@/components/solana/solana-provider';
import {AppProvider} from '@/providers/app-provider'
import { ReactQueryProvider } from './react-query-provider';

export const metadata = {
  title: 'team-shadow',
  description: 'Generated by create-solana-dapp',
};

const links: { label: string; path: string }[] = [
  // { label: 'Account', path: '/account' },
  // { label: 'Clusters', path: '/clusters' },
  // { label: 'TeamShadow Program', path: '/team-shadow' },
  { label: 'Lead Trader', path: '/lead-trader' },
];

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ReactQueryProvider>
          <ClusterProvider>
            <SolanaProvider>
              <AppProvider>
                <UiLayout links={links}>{children}</UiLayout>
              </AppProvider>
            </SolanaProvider>
          </ClusterProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
